[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "fovi"
description = "A foveated interface for deep vision models"
requires-python = ">=3.9"
dynamic = ["version", "dependencies", "optional-dependencies"]

[tool.hatch.version]
path = "fovi/_version.py"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.metadata.hooks.requirements_txt]
files = ["fovi/requirements.txt", "requirements-warp.txt"]

[tool.hatch.metadata.hooks.requirements_txt.optional-dependencies]
models = ["requirements-models.txt"]
training = ["requirements-models.txt", "requirements-training.txt"]
ffcv = ["requirements-ffcv.txt"]
all = ["requirements-models.txt", "requirements-training.txt", "requirements-ffcv.txt"]
warp = ["requirements-warp.txt"]

[tool.hatch.build.targets.wheel]
packages = ["fovi"]
