[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "fovi"
version = "0.0.0"
description = "A foveated interface for deep vision models"
requires-python = ">=3.9"
dynamic = ["dependencies"]

[tool.hatch.metadata.hooks.requirements_txt]
files = ["fovi/requirements.txt"]

[tool.hatch.build.targets.wheel]
packages = ["fovi"]
